### ISSUE TITLE
#01 Temperature Convertor

### ISSUE THREAD

**Issue by HarshitMahara** [HarshitMahara/Test#2]
In the Java folder, you will find tempconv.java file.
You have to write down the code to convert temperature in degree C to degree F and kelvin .

Also change the name of the file from tempconv.java to tempconvertor.java

**Comment by Harshal662** [comment]
plz assign it to me

**Comment by GoodGuyPJ** [comment]
can i contribute to this

**Comment by HarshitMahara** [comment]
@Harshal662 @GoodGuyPJ  Anybody can contribute in this. After resolving the issue, you must submit the pull request. Your pull request will be merged once your solution has been validated.
